<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit203578f03c144c16cfca98159be07452
{
    public static $prefixesPsr0 = array (
        'o' => 
        array (
            'org\\bovigo\\vfs' => 
            array (
                0 => __DIR__ . '/..' . '/mikey179/vfsStream/src/main/php',
            ),
        ),
    );

    public static $classMap = array (
        'Format' => __DIR__ . '/..' . '/chriskacerguis/codeigniter-restserver/application/libraries/Format.php',
        'Restserver\\Libraries\\REST_Controller' => __DIR__ . '/..' . '/chriskacerguis/codeigniter-restserver/application/libraries/REST_Controller.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit203578f03c144c16cfca98159be07452::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit203578f03c144c16cfca98159be07452::$classMap;

        }, null, ClassLoader::class);
    }
}
